'use strict';

const categoryData = {
  'Programming & Software': {
    activities: [
      'Build a full-stack CRUD application',
      'Design and optimize a relational database',
      'Create REST APIs with authentication',
      'Deploy an application to the cloud',
      'Perform code review with instructor feedback',
      'Solve algorithm challenges in timed practice',
    ],
    toolsList: [
      'VS Code',
      'Git & GitHub',
      'MySQL / PostgreSQL',
      'Node.js / Python',
      'Postman (API testing)',
      'Docker basics',
      'Linux CLI',
      'Cloud platform (AWS/GCP basics)',
    ],
    jobs: [
      { title: 'Software Developer', salary: '₹4–12 LPA', desc: 'Build and maintain web/desktop applications' },
      { title: 'Backend Engineer', salary: '₹6–18 LPA', desc: 'Design server logic, databases and APIs' },
      { title: 'Database Admin', salary: '₹5–14 LPA', desc: 'Manage, optimize and secure databases' },
      { title: 'Full-Stack Developer', salary: '₹5–20 LPA', desc: 'Own the entire application stack' },
      { title: 'DevOps Engineer', salary: '₹8–22 LPA', desc: 'Automate deployment and infrastructure' },
      { title: 'QA Engineer', salary: '₹3–10 LPA', desc: 'Test and ensure software quality' },
    ],
    roadmap: [
      { step: 1, phase: 'Foundations', desc: 'Core syntax, logic, data types and control flow' },
      { step: 2, phase: 'Core Concepts', desc: 'OOP, data structures, algorithms, APIs' },
      { step: 3, phase: 'Practical Projects', desc: 'Apply skills in guided real-world mini-projects' },
      { step: 4, phase: 'Advanced Topics', desc: 'Frameworks, cloud, deployment and advanced patterns' },
      { step: 5, phase: 'Career Launch', desc: 'Portfolio review, mock interviews, job applications' },
    ],
    whoShouldEnroll: [
      'Beginners with no prior coding experience looking to start a tech career',
      'IT graduates wanting to upgrade their practical programming skills',
      'Working professionals seeking a career switch into software development',
      'Entrepreneurs who want to understand and communicate with their dev teams',
      'Anyone aiming for placements at software companies or tech startups',
    ],
    enrichedFaqs: [
      { q: 'Do I need prior coding knowledge?', a: 'No. The course starts from fundamentals and builds up progressively — no prior experience required.' },
      { q: 'What kind of projects will I build?', a: 'You will build real-world applications including CRUD apps, REST APIs, and a capstone portfolio project.' },
      { q: 'Is placement assistance provided?', a: 'Yes. Placement support including resume reviews, mock interviews and job referrals is included for all enrolled students.' },
      { q: 'How long is the course?', a: 'Duration varies by module, but each session is live and one-on-one, letting you progress at your ideal pace.' },
      { q: 'Will I receive a certificate?', a: 'Yes. An Osian Academy certificate is awarded upon successful completion, recognised by industry partners.' },
    ],
  },

  'Design & Animation': {
    activities: [
      'Create a complete brand identity from scratch',
      'Animate a 30-second motion graphics clip',
      'Design UI wireframes and prototypes in Figma',
      'Build a 3D scene with lighting and rendering',
      'Create a video edit with transitions and effects',
      'Design a poster campaign for a mock brand',
    ],
    toolsList: [
      'Adobe Photoshop',
      'Adobe Illustrator',
      'Adobe After Effects',
      'Figma / CorelDRAW',
      '3ds Max / Blender',
      'Adobe Premiere Pro',
      'AutoCAD (for design tracks)',
      'Canva Pro',
    ],
    jobs: [
      { title: 'Graphic Designer', salary: '₹3–10 LPA', desc: 'Create visual content for print and digital media' },
      { title: 'UI/UX Designer', salary: '₹5–16 LPA', desc: 'Design intuitive user interfaces and experiences' },
      { title: 'Motion Graphics Artist', salary: '₹4–12 LPA', desc: 'Animate visuals for video, web and broadcast' },
      { title: '3D Artist / Animator', salary: '₹4–15 LPA', desc: 'Create three-dimensional art for games, film and ads' },
      { title: 'Art Director', salary: '₹8–22 LPA', desc: 'Lead creative direction for campaigns and brands' },
      { title: 'Video Editor', salary: '₹3–9 LPA', desc: 'Assemble and polish video content for clients' },
    ],
    roadmap: [
      { step: 1, phase: 'Design Principles', desc: 'Colour theory, typography, layout fundamentals' },
      { step: 2, phase: 'Software Mastery', desc: 'Hands-on with industry tools and workflows' },
      { step: 3, phase: 'Portfolio Projects', desc: 'Design real briefs for a diverse portfolio' },
      { step: 4, phase: 'Specialisation', desc: 'Motion, 3D, UI/UX or branding track' },
      { step: 5, phase: 'Industry Ready', desc: 'Client pitching, freelancing setup, job placement' },
    ],
    whoShouldEnroll: [
      'Creative individuals looking to turn their artistic talent into a professional career',
      'Marketing and communications professionals wanting stronger visual skills',
      'Students seeking career opportunities in the growing creative industry',
      'Freelancers who want to expand their design and animation service offerings',
      'Business owners who need to create compelling visual content independently',
    ],
    enrichedFaqs: [
      { q: 'Do I need a design background to enroll?', a: 'No. The course starts from basic design principles — passion for creativity is all you need.' },
      { q: 'Which software will be covered?', a: 'Adobe Photoshop, Illustrator, After Effects, Figma, Premiere Pro and more, depending on your track.' },
      { q: 'Can I freelance after this course?', a: 'Absolutely. The curriculum includes freelancing strategy, client communication and portfolio building.' },
      { q: 'Is a good laptop required?', a: 'A laptop with at least 8 GB RAM is recommended. Our team can advise on optimal setup before you start.' },
      { q: 'Will I get placement support?', a: 'Yes. Placement assistance is included, covering both full-time roles and freelance opportunities.' },
    ],
  },

  'Networking, Hardware & Engineering': {
    activities: [
      'Configure a local area network from scratch',
      'Diagnose and repair a hardware fault',
      'Set up a server with roles and permissions',
      'Simulate a network attack and harden defences',
      'Build and program a basic robotics circuit',
      'Create a CAD drawing for a real-world component',
    ],
    toolsList: [
      'Cisco Packet Tracer',
      'Windows Server',
      'Linux (Ubuntu)',
      'Wireshark',
      'AutoCAD / SolidWorks',
      'Arduino / Raspberry Pi',
      'VMware / VirtualBox',
      'TCP/IP protocol suite',
    ],
    jobs: [
      { title: 'Network Engineer', salary: '₹4–14 LPA', desc: 'Design and manage enterprise network infrastructure' },
      { title: 'Hardware Technician', salary: '₹3–8 LPA', desc: 'Install, maintain and troubleshoot hardware systems' },
      { title: 'Cybersecurity Analyst', salary: '₹6–18 LPA', desc: 'Protect systems and networks from threats' },
      { title: 'System Administrator', salary: '₹4–12 LPA', desc: 'Manage servers, users and IT operations' },
      { title: 'CAD/CAM Engineer', salary: '₹3–9 LPA', desc: 'Design precision components using CAD software' },
      { title: 'IoT Engineer', salary: '₹5–14 LPA', desc: 'Build and deploy connected device solutions' },
    ],
    roadmap: [
      { step: 1, phase: 'Core Fundamentals', desc: 'Hardware components, OSI model, IP addressing basics' },
      { step: 2, phase: 'Configuration Labs', desc: 'Hands-on switch, router and server configuration' },
      { step: 3, phase: 'Security & Monitoring', desc: 'Firewalls, intrusion detection and network analysis' },
      { step: 4, phase: 'Advanced Engineering', desc: 'Cloud networking, IoT integration, CAD/robotics projects' },
      { step: 5, phase: 'Certification & Placement', desc: 'Exam prep, portfolio projects, job application support' },
    ],
    whoShouldEnroll: [
      'Students pursuing a career in IT infrastructure, networking or engineering',
      'Computer science graduates looking to specialise in hardware or security',
      'Working technicians wanting to formalise and advance their skills',
      'Engineering students seeking practical CAD and electronics exposure',
      'Professionals targeting cybersecurity or cloud networking roles',
    ],
    enrichedFaqs: [
      { q: 'Do I need hardware for the labs?', a: 'Simulation tools like Cisco Packet Tracer and VMware are used for most labs; physical kits are provided where needed.' },
      { q: 'Does the course cover cybersecurity?', a: 'Yes. Network security, ethical hacking basics and hardening techniques are integral parts of the curriculum.' },
      { q: 'Are industry certifications covered?', a: 'The curriculum aligns with CompTIA A+, Network+ and Cisco CCNA pathways, helping you prepare for these exams.' },
      { q: 'Can I work in cloud networking after this course?', a: 'Yes. Cloud networking concepts are covered, positioning you for roles in AWS, Azure and GCP infrastructure.' },
      { q: 'Is placement assistance available?', a: 'Yes. Placement support is included for all enrolled students upon course completion.' },
    ],
  },

  'Kids Programs': {
    activities: [
      'Complete a speed arithmetic challenge',
      'Build a basic robot with our kit',
      'Create your first Scratch animation',
      'Solve a mental maths puzzle',
      'Design a creative poster using Paint tools',
      'Present a mini project to classmates',
    ],
    toolsList: [
      'Abacus',
      'Scratch (MIT)',
      'Python basics',
      'MS Paint / Basic design tools',
      'Robot kits',
      'Simple electronics kits',
    ],
    jobs: [
      { title: 'Future Software Developer', salary: 'Foundation skills', desc: 'Early coding builds logical thinking for tech careers' },
      { title: 'Young Robotics Engineer', salary: 'STEM pathway', desc: 'Robotics sparks interest in mechanical and electrical engineering' },
      { title: 'Creative Designer', salary: 'Creative pathway', desc: 'Digital art and design skills open creative career doors' },
      { title: 'Competitive Maths Scholar', salary: 'Academic pathway', desc: 'Abacus and mental maths build speed and accuracy for academics' },
      { title: 'Young Entrepreneur', salary: 'Business pathway', desc: 'Early tech literacy builds confidence for future ventures' },
      { title: 'STEM Researcher', salary: 'Research pathway', desc: 'Hands-on science and coding lay the research foundation' },
    ],
    roadmap: [
      { step: 1, phase: 'Discovery', desc: 'Introduction to tools, fun challenges and exploration' },
      { step: 2, phase: 'Skill Building', desc: 'Structured exercises in coding, maths or design' },
      { step: 3, phase: 'Guided Projects', desc: 'Create small animations, games or circuits with instructor help' },
      { step: 4, phase: 'Creative Expression', desc: 'Independent mini-projects reflecting personal interests' },
      { step: 5, phase: 'Showcase', desc: 'Present completed work to peers and parents with pride' },
    ],
    whoShouldEnroll: [
      'Children aged 6–16 who are curious about technology and computers',
      'Kids who want to learn coding, robotics or creative digital skills',
      'Parents looking for structured after-school STEM enrichment',
      'Students who want a competitive edge in maths and logical reasoning',
      'Young learners who enjoy hands-on building and problem-solving activities',
    ],
    enrichedFaqs: [
      { q: 'What age group is this program for?', a: 'Our Kids Programs cater to children from age 6 to 16, with level-appropriate content for each group.' },
      { q: 'Is prior tech knowledge required?', a: 'Not at all. Programs begin from complete basics and use fun, engaging methods suited for young learners.' },
      { q: 'How long are the sessions?', a: 'Sessions are typically 45–60 minutes, designed to maintain concentration and enthusiasm in younger learners.' },
      { q: 'Will my child receive a certificate?', a: 'Yes. A completion certificate from Osian Academy is awarded, which children can add to their academic portfolio.' },
      { q: 'Can parents monitor progress?', a: 'Yes. Regular progress updates and performance reviews are shared with parents at scheduled intervals.' },
    ],
  },

  'Accounting, Finance & Office Skills': {
    activities: [
      'Prepare a full set of accounts in Tally Prime',
      'File a mock GST return end-to-end',
      'Create a financial analysis dashboard in Excel',
      'Process payroll for a simulated company',
      'Set up and manage an SAP module',
      'Prepare a business plan with financial projections',
    ],
    toolsList: [
      'Tally Prime / ERP9',
      'SAP FICO',
      'MS Excel (Advanced)',
      'QuickBooks',
      'Busy Accounting',
      'PowerPoint / Word Advanced',
      'ZOHO Books',
      'Google Sheets',
    ],
    jobs: [
      { title: 'Accountant / Jr. Accountant', salary: '₹3–8 LPA', desc: 'Manage day-to-day financial records and reconciliations' },
      { title: 'Finance Analyst', salary: '₹5–14 LPA', desc: 'Analyse financial data to guide business decisions' },
      { title: 'Tally Operator', salary: '₹2–5 LPA', desc: 'Handle accounts using Tally in SME environments' },
      { title: 'Tax Consultant', salary: '₹4–12 LPA', desc: 'Advise businesses and individuals on tax compliance' },
      { title: 'SAP Consultant', salary: '₹6–20 LPA', desc: 'Implement and support SAP ERP modules for enterprises' },
      { title: 'Office Administrator', salary: '₹2–6 LPA', desc: 'Manage office operations, documentation and coordination' },
    ],
    roadmap: [
      { step: 1, phase: 'Accounting Basics', desc: 'Bookkeeping, ledgers, trial balance and financial statements' },
      { step: 2, phase: 'Software Training', desc: 'Hands-on with Tally, Excel and accounting platforms' },
      { step: 3, phase: 'Taxation & Compliance', desc: 'GST filing, TDS, income tax and audit preparation' },
      { step: 4, phase: 'Advanced Modules', desc: 'SAP FICO, financial modelling and business analytics' },
      { step: 5, phase: 'Career Readiness', desc: 'Interview prep, practical assessments, placement support' },
    ],
    whoShouldEnroll: [
      'Commerce students and graduates looking for accounting job placements',
      'Working professionals seeking to upgrade to advanced accounting software skills',
      'Business owners who want to manage their own accounts and tax filings',
      'Administrative staff wanting to formalise their financial knowledge',
      'Anyone targeting roles in banking, finance, audit or corporate accounts',
    ],
    enrichedFaqs: [
      { q: 'Is prior accounting knowledge required?', a: 'Basic awareness of commerce is helpful, but the course starts from foundational accounting concepts.' },
      { q: 'Which version of Tally is taught?', a: 'Tally Prime (latest version) is the primary focus, with reference to ERP9 for legacy system awareness.' },
      { q: 'Does the course cover GST and taxation?', a: 'Yes. GST filing, TDS computation, income tax returns and compliance workflows are core curriculum components.' },
      { q: 'Will SAP training be included?', a: 'Yes. SAP FICO fundamentals and navigation are covered in the advanced module.' },
      { q: 'Is a certificate provided?', a: 'Yes. An Osian Academy certificate is awarded, widely recognised by accounting firms and corporate employers.' },
    ],
  },

  'Data, AI & Digital Marketing': {
    activities: [
      'Analyse a real dataset and present insights',
      'Build and train a machine learning model',
      'Run a complete Google Ads campaign simulation',
      'Create an SEO audit and improvement plan',
      'Build a data dashboard in Power BI / Tableau',
      'Design and A/B test a landing page',
    ],
    toolsList: [
      'Python (Pandas, NumPy, Sklearn)',
      'Power BI / Tableau',
      'Google Analytics 4',
      'Google Ads / Meta Ads',
      'Jupyter Notebook',
      'SQL for data analysis',
      'TensorFlow basics',
      'Semrush / Ahrefs (for SEO)',
    ],
    jobs: [
      { title: 'Data Analyst', salary: '₹5–16 LPA', desc: 'Extract and communicate insights from complex datasets' },
      { title: 'Digital Marketing Manager', salary: '₹4–14 LPA', desc: 'Plan and execute multi-channel marketing campaigns' },
      { title: 'ML Engineer', salary: '₹8–25 LPA', desc: 'Design and deploy machine learning models at scale' },
      { title: 'SEO/SEM Specialist', salary: '₹3–10 LPA', desc: 'Improve search visibility and manage paid search campaigns' },
      { title: 'Business Intelligence Analyst', salary: '₹6–18 LPA', desc: 'Build dashboards and reports to drive business strategy' },
      { title: 'Social Media Manager', salary: '₹3–9 LPA', desc: 'Manage brand presence and engagement across social platforms' },
    ],
    roadmap: [
      { step: 1, phase: 'Data Fundamentals', desc: 'Statistics, data types, Excel/SQL data wrangling' },
      { step: 2, phase: 'Analytics & Visualisation', desc: 'Power BI, Tableau, Google Analytics dashboards' },
      { step: 3, phase: 'Marketing Channels', desc: 'SEO, PPC, social media, email and content marketing' },
      { step: 4, phase: 'AI & ML Introduction', desc: 'Python for data science, ML algorithms and model building' },
      { step: 5, phase: 'Campaign & Career', desc: 'Live campaign projects, portfolio preparation, placement support' },
    ],
    whoShouldEnroll: [
      'Graduates and professionals seeking careers in data analytics or digital marketing',
      'Marketing professionals who want to add data and AI skills to their toolkit',
      'Business owners who want to run their own data-driven digital campaigns',
      'IT professionals wanting to transition into data science or ML engineering',
      'Students who want high-paying tech-adjacent careers without deep coding background',
    ],
    enrichedFaqs: [
      { q: 'Do I need programming experience?', a: 'No prior programming is needed. Python basics are taught from scratch as part of the data/AI track.' },
      { q: 'Is digital marketing and data science combined?', a: 'Yes. The course blends both disciplines, giving you a full-funnel skill set that is highly sought after.' },
      { q: 'Which tools will I learn?', a: 'Python, Power BI, Google Analytics, Google Ads, Tableau, SQL and more are covered in practical sessions.' },
      { q: 'Can I freelance as a digital marketer after this course?', a: 'Absolutely. Freelancing strategy, client acquisition and portfolio building are included in the curriculum.' },
      { q: 'Is placement support available?', a: 'Yes. Dedicated placement assistance for both data analyst and digital marketing roles is provided.' },
    ],
  },
};

const defaultData = {
  activities: [
    'Complete a structured hands-on project',
    'Apply concepts in a guided practical session',
    'Review and improve work with instructor feedback',
    'Collaborate on a real-world simulation exercise',
    'Build a portfolio piece demonstrating your skills',
    'Take a timed assessment to measure progress',
  ],
  toolsList: [
    'MS Office Suite',
    'Google Workspace',
    'Industry-specific software',
    'Communication tools',
    'Project management tools',
    'Presentation software',
    'Cloud storage platforms',
    'Video conferencing tools',
  ],
  jobs: [
    { title: 'Junior Professional', salary: '₹2–6 LPA', desc: 'Entry-level role building domain expertise' },
    { title: 'Senior Specialist', salary: '₹5–14 LPA', desc: 'Lead projects with deep subject matter knowledge' },
    { title: 'Team Lead', salary: '₹6–16 LPA', desc: 'Manage teams and deliver on business objectives' },
    { title: 'Consultant', salary: '₹5–18 LPA', desc: 'Advise organisations in your area of expertise' },
    { title: 'Manager', salary: '₹8–22 LPA', desc: 'Oversee operations and drive strategic initiatives' },
    { title: 'Freelancer / Entrepreneur', salary: 'Variable', desc: 'Run your own practice or client-based business' },
  ],
  roadmap: [
    { step: 1, phase: 'Foundations', desc: 'Core concepts, terminology and introductory skills' },
    { step: 2, phase: 'Skill Building', desc: 'Structured learning with guided exercises and assessments' },
    { step: 3, phase: 'Applied Practice', desc: 'Real-world projects and instructor-reviewed assignments' },
    { step: 4, phase: 'Advanced Topics', desc: 'Deeper dives, edge cases and industry best practices' },
    { step: 5, phase: 'Career Launch', desc: 'Portfolio review, mock interviews, placement support' },
  ],
  whoShouldEnroll: [
    'Students and graduates seeking practical, job-ready skills',
    'Working professionals looking to upskill or change careers',
    'Entrepreneurs wanting to deepen domain knowledge',
    'Anyone seeking structured learning with expert mentorship',
    'Individuals targeting better career prospects and higher salaries',
  ],
  enrichedFaqs: [
    { q: 'Is this course suitable for beginners?', a: 'Yes. The course is designed to accommodate learners at various levels, starting from fundamentals.' },
    { q: 'Are sessions live or recorded?', a: 'Sessions are live and one-on-one, ensuring personalised attention and flexible scheduling.' },
    { q: 'Is placement assistance included?', a: 'Yes. Osian Academy provides dedicated placement support to help you secure relevant job opportunities.' },
    { q: 'How long does the course take?', a: 'Duration depends on the module, but live sessions are paced to your learning speed.' },
    { q: 'Will I receive a certificate?', a: 'Yes. An Osian-certified completion certificate is awarded to all students who finish the course.' },
  ],
};

function enrichCourse(course) {
  const cat = String(course.category || '').trim();
  const data = categoryData[cat] || defaultData;

  return {
    ...course,
    snapshot: {
      mode: '100% Online',
      sessions: 'Live 1-on-1',
      support: 'Placement Included',
      cert: 'Osian Certified',
    },
    activities: data.activities,
    toolsList: data.toolsList,
    jobs: data.jobs,
    roadmap: data.roadmap,
    whoShouldEnroll: data.whoShouldEnroll,
    enrichedFaqs: data.enrichedFaqs,
  };
}

module.exports = { enrichCourse };
